/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttachField: typeof import('./src/components/form/AttachField.vue')['default']
    CriterioRow: typeof import('./src/components/autoevaluacion/CriterioRow.vue')['default']
    DocConnections: typeof import('./src/components/form/DocConnections.vue')['default']
    EstandarCard: typeof import('./src/components/autoevaluacion/EstandarCard.vue')['default']
    FieldInput: typeof import('./src/components/form/FieldInput.vue')['default']
    LinkField: typeof import('./src/components/form/LinkField.vue')['default']
    NivelSelect: typeof import('./src/components/autoevaluacion/NivelSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
