# BASE_IMAGE se deriva de la imagen backend activa; no usar un default ni un tag hardcodeado.
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
COPY --chown=frappe:frappe . /home/frappe/frappe-bench/apps/sgc
RUN cd /home/frappe/frappe-bench && bench build --app sgc

